#!/usr/bin/env bash

# monitor
xrandr --output eDP1 --gamma 0.9:0.8:0.8 &

# wallpaper
hsetroot -solid $C_8
if [[ -f "$THEME/wallpaper" ]] ; then hsetroot -cover $THEME/wallpaper & fi

# cursor
xsetroot -cursor_name left_ptr
