#!/usr/bin/env bash

. "$THEME/colors"

declare -A c
declare -a keys=(
	"C_0"
	"C_1"
	"C_2"
	"C_3"
	"C_4"
	"C_5"
	"C_6"
	"C_7"
	"C_8"
	"C_9"
	"C_10"
	"C_11"
	"C_12"
	"C_13"
	"C_14"
	"C_15"
	"C_BG"
	"C_BG_DIM"
	"C_FG"
	"C_FG_DIM"
	"C_UNAV"
	"C_UNAV_DIM"
	"C_URG"
	"C_URG_DIM"
)
for k in ${keys[@]} ; do
	# k ey
	# v alue
	if [ -z ${k+x} ] ; then eval "$k=#ffffff" ; fi
	eval "v=\$$k"
	# insert into theme array
	c[$k]=$v
done

reg "c" ".Xresources" "#define %k% %v%"
reg "c" "envars" "export %k%=\"%v%\""

# apply to X
xrdb -merge -I$HOME $HOME/.Xresources
