#!/usr/bin/env perl

use strict;
use warnings;

sub on_start {
    my ($self) = @_;
    $self->{bg_focused} = $self->x_resource('background-focused');
    $self->{bg_unfocused} = $self->x_resource('background-unfocused');

    ()
}

sub on_focus_in {
    my ($self) = @_;
    my $octetsbg = $self->locale_encode ("\033]11;$self->{bg_focused}\007");
    $self->cmd_parse ($octetsbg);
    my $octetsborder = $self->locale_encode ("\033]15;$self->{bg_focused}\007");
    $self->cmd_parse ($octetsborder);

    ()
}

sub on_focus_out {
    my ($self, $term) = @_;
    my $octetsbg = $self->locale_encode ("\033]11;$self->{bg_unfocused}\007");
    $self->cmd_parse ($octetsbg);
    my $octetsborder = $self->locale_encode ("\033]15;$self->{bg_unfocused}\007");
    $self->cmd_parse ($octetsborder);
    
    ()
}
