#!/usr/bin/env bash
### generate files used in places
### like bspwmrc and .bashrc

gens=(
	".Xresources"
	"envars"
)
for g in ${gens[@]} ; do
	f="$DIR/gen/$g"
	if [[ -f "$f" ]] ; then touch "$f" ; fi
	echo -n "" > $f
done
rep () {
	echo $(sed "s|%$2%|$3|" <<< $1)
}
reg () { # @array @file name @match string
	local -n keys=$1
	for k in ${!keys[@]} ; do
		local step1="$(rep "$3" "v" "${keys[$k]}")"
		local step2="$(rep "$step1" "k" "$k")"
		echo "$step2" >> $DIR/gen/$2
	done
} 
