#!/bin/sh

black=\#000000
black_faded=\#262626
red=\#ff0000
red_faded=\#ff4d4d
orange=\#ff6600
orange_faded=\#ff944d
yellow=\#ffff00
yellow_faded=\#ffff4d
green=\#00ff00
green_faded=\#4dff4d
blue=\#0000ff
blue_faded=\#4d4dff
purple=\#ff0066
purple_faded=\#ff4d94
white=\#ffffff
white_faded=\#d9d9d9
