#!/usr/bin/env bash

# ---
# desktops

bspc monitor -d 1 2 3 4 5 6 7 8

# ---
# spacing

bspc config border_width 3
bspc config window_gap   16

# ---
# display settings

bspc config split_ratio        0.50
bspc config borderless_monocle false
bspc config gapless_monocle    false

# ---
# colors

. "$HOME/.config/themes/active/bspwm"

bspc config normal_border_color   "$C_BG"
bspc config active_border_color   "$C_BG_DIM"
bspc config focused_border_color  "$C_FG_DIM"
bspc config presel_feedback_color "$C_BG_DIM"

# ---
# window

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'

# ---
# external settings

# wallpaper
hsetroot -solid $black_bright & 
hsetroot -cover ~/.config/themes/active/wallpaper &
# change default cursor
xsetroot -cursor_name left_ptr &

echo "bspwmrc loaded!"
