#!/usr/bin/env bash

# env vars dont load since our chain starts
# with xinit, so here i include the theme's colors
. $HOME/.config/themes/active/colors

# ---
# desktops

bspc monitor -d 1 2 3 4 5 6 7 8

# ---
# spacing

bspc config border_width 3
bspc config window_gap   16

# ---
# display settings

bspc config split_ratio        0.50
bspc config borderless_monocle false
bspc config gapless_monocle    false

# ---
# colors

bspc config normal_border_color   "$C_BG"
bspc config active_border_color   "$C_BG_DIM"
bspc config focused_border_color  "$C_FG_DIM"
bspc config presel_feedback_color "$C_BG_DIM"

# ---
# window

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
